### ISSUE TITLE
[Enhancement]  Support for PyLoad

### ISSUE THREAD

**Issue by CodingMask** [Corey-Evans/real-debrid-blackhole#1]
First, thanks for coding this.  I came upon this because I was looking exactly for this functionality.

Enhancement suggestion would be to add support for DL via [PyLoad](https://github.com/pyload/pyload).  PyLoad also supports [hooks](https://github.com/pyload/pyload/wiki/Hooks#interacting-on-events) so it could be used to interact with completed DL's or be setup to trigger after your watchdog finds new content in the blackhole

**Comment by CoreyAU** [comment]
Sorry mate, I'm not really using or maintaining this anymore. Feel free to fork the code but :)
